dinner_guests = ['John Maynard Keynes', 'John Stuart Mill', 'Edmund Burke']
print(f"Hello, {dinner_guests[0]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[1]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[2]}, would you care to come to supper?")
declined = dinner_guests.pop(0)
print(f"Oh no! {declined} can no longer come. We need to invite someone else!")
dinner_guests.append('Friedrich Hayek')
print(f"Hello, {dinner_guests[0]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[1]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[2]}, would you care to come to supper?")
print("We found a bigger table, so we can invite more guests!")
dinner_guests.insert(0, 'Karl Marx')
dinner_guests.insert(2, 'Karl Popper')
dinner_guests.append('John Locke')
print(f"We now have {len(dinner_guests)} guests!")
print(f"Hello, {dinner_guests[0]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[1]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[2]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[3]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[4]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[5]}, would you care to come to supper?")