dinner_guests = ['John Maynard Keynes', 'John Stuart Mill', 'Edmund Burke']
print(f"Hello, {dinner_guests[0]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[1]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[2]}, would you care to come to supper?")
declined = dinner_guests.pop(0)
print(f"Oh no! {declined} can no longer come. We need to invite someone else!")
dinner_guests.append('Friedrich Hayek')
print(f"Hello, {dinner_guests[0]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[1]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[2]}, would you care to come to supper?")
print("We found a bigger table, so we can invite more guests!")
dinner_guests.insert(0, 'Karl Marx')
dinner_guests.insert(2, 'Karl Popper')
dinner_guests.append('John Locke')
print(f"We now have {len(dinner_guests)} guests!")
print(f"Hello, {dinner_guests[0]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[1]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[2]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[3]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[4]}, would you care to come to supper?")
print(f"Hello, {dinner_guests[5]}, would you care to come to supper?")
print("Oh no! The table didn't arrive in time. Sorry everyone, we can only have two guests after all!")
print(f"Sorry, {dinner_guests.pop(-1)}, you'll have to come another time!")
print(f"Sorry, {dinner_guests.pop(-1)}, you'll have to come another time!")
print(f"Sorry, {dinner_guests.pop(0)}, you'll have to come another time!")
print(f"Sorry, {dinner_guests.pop(1)}, you'll have to come another time!")
print(f"Hey {dinner_guests[0]}, you're still invited!")
print(f"Hey {dinner_guests[1]}, you're still invited!")
del dinner_guests[0]
del dinner_guests[0]
print(dinner_guests)